### ISSUE TITLE
Error on Build?

### ISSUE THREAD

**Issue by askl56** [wtfutil/wtf#130] opened 2018-06-02 14:29 UTC
#### Summary
Ran Go Get and ran make and ran into error

##### What is the current behaviour?

When running make, errors out with ``` ╍╍  g s g s    wtf  make install                                     │
which wtf | xargs rm || true
go install -ldflags="-X main.version=v0.0.4_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-02T15:28:42+0100"
which wtf
make: *** [install] Error 1```

Go version is `go version go1.10.2 darwin/amd64`

**Comment by International** [comment] 2018-06-02 19:15
Not really sure what `shell` is supposed to be, and it seems that the Makefile is relying on the presence of some environment variables ( maybe zsh or some other shell extensions ). The following change works on my machine:
```
BRANCH := `git rev-parse --abbrev-ref HEAD`

.PHONY: dependencies install run

dependencies:
	go get -v ./...

install:
	which wtf | xargs rm || true
	go install -ldflags="-X main.version=$(git describe --always --abbrev=6)_$(git rev-parse --abbrev-ref HEAD) -X main.date=$(date +%FT%T%z)"
	which wtf

run:
	wtf
```

**Comment by deltaxflux** [comment] 2018-06-02 19:36
@International @askl56 

Well, looks good but this change is not required. First we take a look if the gopath is set.
```
echo $GOPATH
```

If this return empty we have to set the go path first before installing.
```
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

## Installation
Installing `wtf` appears simple. You can follow the instructions there. After you set your go path we will clone this repository using `go`. 

**Note** we are not using git clone here because this could lead to unexpected things like in this case.

### Step: 1
**cloning:**
`go get -u github.com/senorprogrammer/wtf`

## Step: 2
**changing directories:**
`cd $GOPATH/src/github.com/senorprogrammer/wtf`

## Step: 3
**installing**
`make install`

## Step: 4
**testing**
`make run`

### Misc
If this problem still occur, please paste the output of `go wtf.go`. In the most cases, the dependencies are missing.

Regards,

deltax

**Comment by askl56** [comment] 2018-06-02 20:04
I followed those instructions. I have a gopath set (I am a Go developer).

``` ╍╍  g s g s    wtf  go wtf.go                                                                                                                                                                                                                                                                                                                    │
go: unknown subcommand "wtf.go"
Run 'go help' for usage.```

**Comment by deltaxflux** [comment] 2018-06-02 20:13
Interesting... which go version are you using?

**Comment by deltaxflux** [comment] 2018-06-02 20:16
Sorry I mean go run wtf.go.

**Comment by senorprogrammer** [comment] 2018-06-02 23:04
@jmks Which version of Go do you have (`go version`)? `time.Round` (https://golang.org/pkg/time/#Duration.Round) is part of stdlib but perhaps not in the version you've got installed?

**Comment by jmks** [comment] 2018-06-03 00:28
@senorprogrammer I must have misread the version reqs in the README. Was on 1.8 and updating to `go1.10.2 darwin/amd64` got `make install` working fine. Thanks!

**Comment by senorprogrammer** [comment] 2018-06-03 00:39
To be fair, the original version requirements were wrong. The minimum compatible version now appears to be 1.9.2 with some people having success with 1.10.2 and some not. So, congrats! :)

**Comment by askl56** [comment] 2018-06-03 02:37
@deltaxflux `go run wtf.go` runs the program as it should...

**Comment by senorprogrammer** [comment] 2018-06-03 04:15
This is shedding some light on installation issues people are having, and it's likely because of my crap Makefile skills. On my machine (macOS, zsh) without the `shell` in there the `Built` and `Vers` values are not set. It appears that on other configurations, removing `shell` gets it to work (not clear if those values are then set).

So, looks like `shell` is probably the cause of, and solution to, depending on where you stand. Anyone have any deeper/better thoughts on this?

**Comment by deltaxflux** [comment] 2018-06-03 06:34
Well, I don't think that it is about `shell` in general. First I thought that the problem are the env variables. However, this appear to be false. I think there are problems in the Makefile.

Note: Makefiles are very fragile, they are easy to use but they also exit if some problem returned other values bessides 0. This makes error handling nearly impossible.

On my system this line causes the problem (tried on zsh, bash, fish), if wtf appears empty.
`which wtf | xargs rm || true`

If you want I can do this  ( building a install script ) but I'm fine if you only want to use Makefiles.

Regards

**Comment by deltaxflux** [comment] 2018-06-03 06:35
@askl56 

If you are fine we could debug the Makefile. Try to comment out this line: 
`which wtf | xargs rm || true` 

and share results

**Comment by askl56** [comment] 2018-06-03 08:12
Sure, I can also try on my Arch machine and see if it makes a difference. 

Same error:

```
 ╍╍  g s g s    wtf  make install                                                                                                      │
# which wtf | xargs rm || true
go install -ldflags="-X main.version=v0.0.4_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-03T09:12:25+0100"
which wtf
make: *** [install] Error 1
 ╍╍  g s g s    wtf  make install                                                                                         2 ╱ 1s 882ms ┃
go install -ldflags="-X main.version=v0.0.4_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-03T09:12:35+0100"
which wtf
make: *** [install] Error 1

```

**Comment by deltaxflux** [comment] 2018-06-03 08:16
Ok fine, last but no least comment out `which wtf`

**Comment by askl56** [comment] 2018-06-03 08:18
seems to work... 


```
 ╍╍  g s g s    wtf  make install                                                                                                      │
go install -ldflags="-X main.version=v0.0.4_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-03T09:17:39+0100"

```

**Comment by deltaxflux** [comment] 2018-06-03 08:45
@senorprogrammer what do you think?

## Notes
So now what happend:
As I said Makefiles are fragile. Conclusions depend on OS and env.

## Issues
1. The problem is **not** as I thought `which wtf | xargs rm || true`. I made a quick test and it seems to work.  So this is fine, even if it is not elegant.

2. Now we have this line:
`go install -ldflags="-X main.version=v0.0.4_`git rev-parse --abbrev-ref HEAD` -X main.date=2018-06-03T09:12:25+0100"`. This doesn't do what it should do. Maybe @senorprogrammer  can clearify this. What happen is that wtf doesn't get installed. This is why the Makefile fail because of the next line.

3. Since **wtf** doesn't get installed this line will fail:
`which wtf` because it returns 1 instead of 0 because wtf is not found.

Thats why you get this trace.

## How to solve
Maybe I find a work around. I can reproduce this bug on my secound arch linux OS.

Regards,

deltax

**Comment by askl56** [comment] 2018-06-03 08:46
@deltaxflux Happy to look into it as well, but it will be tomorrow as trying to deliver a project today.

**Comment by senorprogrammer** [comment] 2018-06-03 14:51
I'm not marries to having a makefile do the installing, shell script etc. is fine to. I simple use `make install` to have a common interface on all my projects. If that calls out to something else, that's cool also.

**Comment by deltaxflux** [comment] 2018-06-05 09:33
Ok, I will create an installer which support also the existing makefile. If you want you can me assign to this issue.

**Comment by deltaxflux** [comment] 2018-06-14 23:46
The problem is not that first line. The `which wtf` is the problem if wtf isn't installed. So this change doesn't make any difference.

**Comment by senorprogrammer** [comment] 2018-06-25 23:42
I finally have a Linux install to test this against and yeah, `make install` is pretty broken there. Unless you're using `zsh` it really doesn't like the `shell` bits of the `install` command (amongst other things). Will sort that out.

**Comment by ataner** [comment] 2018-08-08 14:30
I have MacOS High Sierra here and make install is very broken here. My $GOPATH/$GOBIN envs are set and make install produces the following output: 

```$ make install -d
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Reading makefile `Makefile'...
Updating makefiles....
 Considering target file `Makefile'.
  Looking for an implicit rule for `Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.o'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.c'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.cc'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.C'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.cpp'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.p'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.f'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.F'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.m'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.r'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.s'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.S'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.sh'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile,v'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `RCS/Makefile,v'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `RCS/Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `s.Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `SCCS/s.Makefile'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.o'.
  Looking for a rule with intermediate file `Makefile.o'.
   Avoiding implicit rule recursion.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.c'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cc'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.C'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cpp'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.p'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.f'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.F'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.m'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.s'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.mod'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `Makefile.o,v'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `RCS/Makefile.o,v'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `RCS/Makefile.o'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `s.Makefile.o'.
   Trying pattern rule with stem `Makefile.o'.
   Trying implicit prerequisite `SCCS/s.Makefile.o'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.c'.
   Looking for a rule with intermediate file `Makefile.c'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.y'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.l'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `Makefile.c,v'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `RCS/Makefile.c,v'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `RCS/Makefile.c'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `s.Makefile.c'.
    Trying pattern rule with stem `Makefile.c'.
    Trying implicit prerequisite `SCCS/s.Makefile.c'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.y'.
    Looking for a rule with intermediate file `Makefile.y'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `Makefile.y,v'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `RCS/Makefile.y,v'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `RCS/Makefile.y'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `s.Makefile.y'.
     Trying pattern rule with stem `Makefile.y'.
     Trying implicit prerequisite `SCCS/s.Makefile.y'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.l'.
    Looking for a rule with intermediate file `Makefile.l'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `Makefile.l,v'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `RCS/Makefile.l,v'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `RCS/Makefile.l'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `s.Makefile.l'.
     Trying pattern rule with stem `Makefile.l'.
     Trying implicit prerequisite `SCCS/s.Makefile.l'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.w'.
    Looking for a rule with intermediate file `Makefile.w'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `Makefile.w,v'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `RCS/Makefile.w,v'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `RCS/Makefile.w'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `s.Makefile.w'.
     Trying pattern rule with stem `Makefile.w'.
     Trying implicit prerequisite `SCCS/s.Makefile.w'.
    Trying pattern rule with stem `Makefile'.
    Rejecting impossible implicit prerequisite `Makefile.w'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cc'.
   Looking for a rule with intermediate file `Makefile.cc'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `Makefile.cc,v'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `RCS/Makefile.cc,v'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `RCS/Makefile.cc'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `s.Makefile.cc'.
    Trying pattern rule with stem `Makefile.cc'.
    Trying implicit prerequisite `SCCS/s.Makefile.cc'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.C'.
   Looking for a rule with intermediate file `Makefile.C'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `Makefile.C,v'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `RCS/Makefile.C,v'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `RCS/Makefile.C'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `s.Makefile.C'.
    Trying pattern rule with stem `Makefile.C'.
    Trying implicit prerequisite `SCCS/s.Makefile.C'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.cpp'.
   Looking for a rule with intermediate file `Makefile.cpp'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `Makefile.cpp,v'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `RCS/Makefile.cpp,v'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `RCS/Makefile.cpp'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `s.Makefile.cpp'.
    Trying pattern rule with stem `Makefile.cpp'.
    Trying implicit prerequisite `SCCS/s.Makefile.cpp'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.p'.
   Looking for a rule with intermediate file `Makefile.p'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.web'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `Makefile.p,v'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `RCS/Makefile.p,v'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `RCS/Makefile.p'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `s.Makefile.p'.
    Trying pattern rule with stem `Makefile.p'.
    Trying implicit prerequisite `SCCS/s.Makefile.p'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.web'.
    Looking for a rule with intermediate file `Makefile.web'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `Makefile.web,v'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `RCS/Makefile.web,v'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `RCS/Makefile.web'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `s.Makefile.web'.
     Trying pattern rule with stem `Makefile.web'.
     Trying implicit prerequisite `SCCS/s.Makefile.web'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.f'.
   Looking for a rule with intermediate file `Makefile.f'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.F'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.r'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `Makefile.f,v'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `RCS/Makefile.f,v'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `RCS/Makefile.f'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `s.Makefile.f'.
    Trying pattern rule with stem `Makefile.f'.
    Trying implicit prerequisite `SCCS/s.Makefile.f'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.F'.
    Looking for a rule with intermediate file `Makefile.F'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `Makefile.F,v'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `RCS/Makefile.F,v'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `RCS/Makefile.F'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `s.Makefile.F'.
     Trying pattern rule with stem `Makefile.F'.
     Trying implicit prerequisite `SCCS/s.Makefile.F'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.r'.
    Looking for a rule with intermediate file `Makefile.r'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile'.
     Rejecting impossible implicit prerequisite `Makefile.l'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `Makefile.r,v'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `RCS/Makefile.r,v'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `RCS/Makefile.r'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `s.Makefile.r'.
     Trying pattern rule with stem `Makefile.r'.
     Trying implicit prerequisite `SCCS/s.Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.F'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.m'.
   Looking for a rule with intermediate file `Makefile.m'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.ym'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.lm'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `Makefile.m,v'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `RCS/Makefile.m,v'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `RCS/Makefile.m'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `s.Makefile.m'.
    Trying pattern rule with stem `Makefile.m'.
    Trying implicit prerequisite `SCCS/s.Makefile.m'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.ym'.
    Looking for a rule with intermediate file `Makefile.ym'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `Makefile.ym,v'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `RCS/Makefile.ym,v'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `RCS/Makefile.ym'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `s.Makefile.ym'.
     Trying pattern rule with stem `Makefile.ym'.
     Trying implicit prerequisite `SCCS/s.Makefile.ym'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.lm'.
    Looking for a rule with intermediate file `Makefile.lm'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `Makefile.lm,v'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `RCS/Makefile.lm,v'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `RCS/Makefile.lm'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `s.Makefile.lm'.
     Trying pattern rule with stem `Makefile.lm'.
     Trying implicit prerequisite `SCCS/s.Makefile.lm'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.r'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.s'.
   Looking for a rule with intermediate file `Makefile.s'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.S'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `Makefile.s,v'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `RCS/Makefile.s,v'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `RCS/Makefile.s'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `s.Makefile.s'.
    Trying pattern rule with stem `Makefile.s'.
    Trying implicit prerequisite `SCCS/s.Makefile.s'.
    Trying pattern rule with stem `Makefile'.
    Trying implicit prerequisite `Makefile.S'.
    Looking for a rule with intermediate file `Makefile.S'.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Avoiding implicit rule recursion.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `Makefile.S,v'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `RCS/Makefile.S,v'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `RCS/Makefile.S'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `s.Makefile.S'.
     Trying pattern rule with stem `Makefile.S'.
     Trying implicit prerequisite `SCCS/s.Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Rejecting impossible implicit prerequisite `Makefile.S'.
   Trying pattern rule with stem `Makefile'.
   Trying implicit prerequisite `Makefile.mod'.
   Looking for a rule with intermediate file `Makefile.mod'.
    Avoiding implicit rule recursion.
    Avoiding implicit rule recursion.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `Makefile.mod,v'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `RCS/Makefile.mod,v'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `RCS/Makefile.mod'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `s.Makefile.mod'.
    Trying pattern rule with stem `Makefile.mod'.
    Trying implicit prerequisite `SCCS/s.Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.c'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.cc'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.C'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.cpp'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.p'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.f'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.F'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.m'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.r'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.s'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.S'.
  Trying pattern rule with stem `Makefile'.
  Rejecting impossible implicit prerequisite `Makefile.mod'.
  Trying pattern rule with stem `Makefile'.
  Trying implicit prerequisite `Makefile.sh'.
  Looking for a rule with intermediate file `Makefile.sh'.
   Avoiding implicit rule recursion.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `Makefile.sh,v'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `RCS/Makefile.sh,v'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `RCS/Makefile.sh'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `s.Makefile.sh'.
   Trying pattern rule with stem `Makefile.sh'.
   Trying implicit prerequisite `SCCS/s.Makefile.sh'.
  No implicit rule found for `Makefile'.
  Finished prerequisites of target file `Makefile'.
 No need to remake target `Makefile'.
Updating goal targets....
Considering target file `install'.
 File `install' does not exist.
 Finished prerequisites of target file `install'.
Must remake target `install'.
go clean
Putting child 0x7fab9bf00190 (install) PID 54798 on the chain.
Live child 0x7fab9bf00190 (install) PID 54798
Reaping winning child 0x7fab9bf00190 PID 54798
go install -ldflags="-s -w -X main.version=0.2.0-8-g63e9c5 -X main.date=2018-08-08T10:28:29-0400"
Live child 0x7fab9bf00190 (install) PID 54799
Reaping winning child 0x7fab9bf00190 PID 54799
which wtf
Live child 0x7fab9bf00190 (install) PID 54839
Reaping losing child 0x7fab9bf00190 PID 54839
make: *** [install] Error 1
Removing child 0x7fab9bf00190 PID 54839 from chain.``` 

go version go1.10.3 darwin/amd64

**Comment by termlimit** [comment] 2018-08-08 20:10
Installed today with same error noted above. I did:

`sudo ln -s $HOME/go/bin/wtf /usr/local/bin/wtf`

And this allowed `make install` to work correctly.  Not 100% answer, but it fixes it for the install now.

**Comment by andersfylling** [comment] 2019-01-13 18:41
Got an error as well. Seems it's just a PATH issue as mentioned above. Make sure you have `GOPATH` in your `PATH`, and `$GOPATH/bin`.

First trying to install it:
```
$ go get -u github.com/wtfutil/wtf

$ cd go/src/github.com/wtfutil/wtf

$ make install
go clean
go install -ldflags="-s -w -X main.version=0.4.0-32-g48cb7b -X main.date=2019-01-13T19:24:59+0100"
which wtf
which: no wtf in (/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
make: *** [Makefile:12: install] Error 1
```

As you can see there's no wtf in my path. Checking the bin dir of my GOPATH shows that the binary exists.
```
$ cd ~/go/bin

$ ls -lah | grep wtf
-rwxr-xr-x 1 anders users  20M Jan 13 19:25 wtf
```

Permissions are correct and everything, so it seems it just a matter of adding it to the PATH. I use zsh so I update my PATH in ~/.zshrc. 
```
export PATH="${PATH}:${HOME}/go/bin"
```

Restart terminal and it works.


Maybe add a simple check in the Makefile to verify that they have the GOPATH and binary folder setup before they install?

**Comment by senorprogrammer** [comment] 2019-01-13 19:49
Thanks for adding this additional info, that's an excellent suggestion.

**Comment by senorprogrammer** [comment] 2019-01-13 19:57
This commit on `master` now checks for the `GOPATH`. If not set, attempts to set it.

https://github.com/wtfutil/wtf/commit/0f86740a7fdca6963a0f2e4a0bd3b563c644b50a

**Comment by andersfylling** [comment] 2019-01-13 20:05
This commit is great!
But does it give out a warning that their path is not correctly set?

Cause I assume that after the `make install`, they will launch `wtf` and go on to assume it works. Then if they try it in another terminal session they will get an error, as the PATH has not been globally/permanently updated.

**Comment by senorprogrammer** [comment] 2019-01-13 23:47
It should (I haven't actually tested that path as my GOPATH is set). The `$(info...)` lines display statuses as it runs. However it still builds and installs because not having a permanent GOPATH should not prevent that (CI systems may not want that, for instance).

**Comment by senorprogrammer** [comment] 2019-02-22 13:33
Archiving.

**Closed by senorprogrammer** 2019-02-22 13:33 UTC
Labels: 🔍 investigating
