### ISSUE TITLE
Jira widget: single-word status does not show

### ISSUE THREAD

**Issue by lesteenman** [wtfutil/wtf#574] opened 2019-08-30 13:35 UTC
## What's broken?

If an issue has a name that's only a single word, it's not shown. E.g., we have statusses like `Ready for release`, which is shown. `Doing`, however, is hidden.

This seems to be caused by the color formatting. I suspect a single word in square brackets (e.g. `[Doing]`) is parsed as a formatter code, and therefore stripped.

<img width="248" alt="Screenshot 2019-08-30 at 15 36 38" src="https://user-images.githubusercontent.com/963290/64025110-4786be80-cb3c-11e9-926b-92953650e071.png">

I've solved this in a local build by replacing the square brackets with parentheses. See attached screenshot.

<img width="248" alt="Screenshot 2019-08-30 at 15 36 47" src="https://user-images.githubusercontent.com/963290/64025116-4a81af00-cb3c-11e9-9f15-b757f35314c6.png">

If this is an acceptable workaround, I'm willing to make a PR for it.

**Comment by lesteenman** [comment] 2019-08-30 13:41
Alternatively, we could change it to match the original proposal's layout: https://github.com/wtfutil/wtf/issues/203#issuecomment-405304696

**Comment by Seanstoppable** [comment] 2019-08-30 15:47
I think either of those are reasonably. Spacing + different colors make the column differences fairly clear from screenshots.

**Comment by senorprogrammer** [comment] 2019-08-30 15:57
I think you're right about the cause and your solution sounds good to me. A PR would be appreciated, thanks!

**Comment by lesteenman** [comment] 2019-08-31 20:24
When implementing the column-based layout as shown in the original proposal (which I personally prefer), I ran into the issue of column widths, as can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/963290/64068705-04ac1000-cc3c-11e9-885d-9bcb6be861d5.png)

This issue already exists if you have longer issue types, as can be seen above as well.

Having a lot of varying column positions (as in the screenshot), does not make for an easily scannable display. Having everything in view at a glance is one of the main reasons to use WTF for me personally.

I added functionality to first find the longest value in each column, and use that to determine that column's amount of padding. However, there are possible issues with this, mainly the possibility of there being a very long status or type name. 

I would like the opinion of experienced collaborators on this. I would prefer capping the length at e.g. 16 characters, and cutting off the column contents there.

![image](https://user-images.githubusercontent.com/963290/64068834-18587600-cc3e-11e9-9943-dbb3c0d9a176.png)

**Comment by lesteenman** [comment] 2019-08-31 20:27
My main question for now is: 

- do the above examples look acceptable to merge
- should I cap column lengths at a number of characters, or leave it like this

**Comment by lesteenman** [comment] 2019-08-31 20:38
For comparison, this is what capping the max length would look like:

![image](https://user-images.githubusercontent.com/963290/64068943-142d5800-cc40-11e9-87e9-a2b326bf72e5.png)

I do not know if this matches the standards of WTF.

**Comment by senorprogrammer** [comment] 2019-09-01 15:53
Looks good to me. I think that's a reasonable approach until we can get proper table support for sections like this implemented.

**Comment by senorprogrammer** [comment] 2019-09-02 23:04
Fixed by https://github.com/wtfutil/wtf/pull/591

**Closed by senorprogrammer** 2019-09-02 23:04 UTC
Labels: 🐛 bug
