### ISSUE TITLE
Docker does not run: ERROR Could not create the '~/.config/' directory

### ISSUE THREAD

**Issue by Hubbitus** [wtfutil/wtf#821] opened 2020-01-15 22:09 UTC
```
$ ls configs/
sample_config.yml
$ docker run -v $(pwd)/configs:/configs -it wtfutil/wtf wtfutil --config=/configs/sample_config.yml

ERROR Could not create the '~/.config/' directory.

Error: mkdir : no such file or directory
```

**Comment by Seanstoppable** [comment] 2020-01-24 04:30
This seems to be due to some old golang bug that seems to be fixed, in that it can't find a user and then bombs out (on linux).

I currently worked around this by setting `-e USER=wtfutil`, and am debugging some more to understand before comitting a better fix.

**Comment by senorprogrammer** [comment] 2020-02-23 15:23
Is this still an issue, given the docker improvements that were added in v0.26.0?

**Comment by senorprogrammer** [comment] 2020-03-16 03:23
Closing this due to lack of reproducibility and response.

**Closed by senorprogrammer** 2020-03-16 03:23 UTC
Labels: 🐛 bug

**Comment by Hubbitus** [comment] 2020-04-27 16:57
Is there commit for better fix?

**Comment by Hubbitus** [comment] 2020-05-07 15:39
@senorprogrammer, what responce are you waiting?

**Comment by senorprogrammer** [comment] 2020-05-07 16:12
I personally don't use docker to run WTF so I'm waiting for someone who can a) reproduce, b) inform whether or not @Seanstoppable's suggested fix, mentioned above, works, or c) provide a solution for it.
