### ISSUE TITLE
dynamic_sizing.yml sample config seems broken (or incomplete)

### ISSUE THREAD

**Issue by nathanchererecordunion** [wtfutil/wtf#764] opened 2019-11-25 12:20 UTC
## What's broken?

When running the dynamic_sizing.yml config, the following error occurs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55e74d2d9359]

goroutine 1 [running]:
github.com/olebedev/config.(*Config).String(0x0, 0x55e74e5cad32, 0xa, 0x180, 0x55e74f05ad00, 0xc0006d2f01, 0xc000570300)
	github.com/olebedev/config@v0.0.0-20190528211619-364964f3a8e4/config.go:300 +0x39
github.com/olebedev/config.(*Config).UString(0x0, 0x55e74e5cad32, 0xa, 0xc0006d3120, 0x1, 0x1, 0x55e74ed5b560, 0x55e74d1589c2)
	github.com/olebedev/config@v0.0.0-20190528211619-364964f3a8e4/config.go:315 +0x45
github.com/wtfutil/wtf/cfg.NewCommonSettingsFromModule(0xc0004fc870, 0x7, 0x55e74e5b2253, 0x5, 0x0, 0xc000401060, 0xc000400d40, 0x5)
	github.com/wtfutil/wtf@/cfg/common_settings.go:66 +0xe7
github.com/wtfutil/wtf/modules/power.NewSettingsFromYAML(...)
	github.com/wtfutil/wtf@/modules/power/settings.go:19
github.com/wtfutil/wtf/app.MakeWidget(0xc0006a4700, 0xc0006f90b0, 0xc0004fc870, 0x7, 0xc000400d40, 0x0, 0x9acb4f7d27c3)
	github.com/wtfutil/wtf@/app/widget_maker.go:195 +0xbc4
github.com/wtfutil/wtf/app.MakeWidgets(0xc0006a4700, 0xc0006f90b0, 0xc000400d40, 0xc0006d3d20, 0x1, 0x1)
	github.com/wtfutil/wtf@/app/widget_maker.go:266 +0x12c
github.com/wtfutil/wtf/app.NewWtfApp(0xc0006a4700, 0xc000400d40, 0xc0005de750, 0x23, 0x1)
	github.com/wtfutil/wtf@/app/wtf_app.go:47 +0x2e9
main.main()
	github.com/wtfutil/wtf@/main.go:69 +0x27a

```

**Comment by senorprogrammer** [comment] 2019-11-27 13:54
@nathanchererecordunion I'm not able to reproduce this yet. Could you provide a bit more information?

How are you running `dynamic_sizing.yml`? From source like 
```
    ❯ go run . --config=_sample_configs/dynamic_sizing.yml
```
or against the compiled binary?

Which OS are you on, and which version of Go are you running (`go version`)?

**Comment by senorprogrammer** [comment] 2019-12-14 05:27
Closing as cannot reproduce and no follow-up information. If this is still an issue, feel free to re-open.

**Closed by senorprogrammer** 2019-12-14 05:27 UTC
Labels: 🐛 bug

**Comment by nathanchererecordunion** [comment] 2019-12-20 14:52
It's working as of latest update, sorry for delayed response

**Comment by senorprogrammer** [comment] 2019-12-20 17:00
Excellent, I suspected as much. Thanks for confirming.
