### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by ejdunn2001** [wtfutil/wtf#1104] opened 2021-09-08 12:29 UTC
## What's broken?
Whenever I try to run I get the following fatal error:
`fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2052ac9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2052ac9e
stack: frame={sp:0x7ffeefbff328, fp:0x7ffeefbff378} stack=[0x7ffeefb803c8,0x7ffeefbff430)
0x00007ffeefbff228:  0x01007ffeefbff248  0x0000000000000004
0x00007ffeefbff238:  0x000000000000001f  0x00007fff2052ac9e
0x00007ffeefbff248:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff258:  0x0000000004036511 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8
0x00007ffeefbff268:  0x00000000057c2037  0x00007ffeefbff2b0
0x00007ffeefbff278:  0x00000000040367c8 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006c66760
0x00007ffeefbff288:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff298:  0x00007ffeefbff2f8  0x0000000004036511 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2a8:  0x0000000006c66760  0x00007ffeefbff2e8
0x00007ffeefbff2b8:  0x0000000004036750 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff2c8
0x00007ffeefbff2c8:  0x0000000004036780 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006c66760
0x00007ffeefbff2d8:  0x0000000004036511 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8
0x00007ffeefbff2e8:  0x00007ffeefbff318  0x0000000004036511 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2f8:  0x00007ffeefbff300  0x0000000004036540 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff308:  0x00000000057dcece  0x000000000000002a
0x00007ffeefbff318:  0x00007ffeefbff368  0x000000000404cc96 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff328: <0x00000000057dcece  0x0000000006c66760
0x00007ffeefbff338:  0x00007ffeefbff3a8  0x0000000004027686 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff348:  0x000000c000246000  0x0000000000002000
0x00007ffeefbff358:  0x0000000000000008  0x000000000406ba00 <runtime.walltime_trampoline+0x0000000000000000>
0x00007ffeefbff368:  0x00007ffeefbff3b0 !0x00007fff2052ac9e
0x00007ffeefbff378: >0x00007ffeefbff3b0  0x0000000006b08000
0x00007ffeefbff388:  0x00000000000004b7  0x0000000004497945 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff398:  0x000000000406c03f <runtime.syscall+0x000000000000001f>  0x000000c0000ed710
0x00007ffeefbff3a8:  0x0000000006c670c0  0x000000c0000ed6e0
0x00007ffeefbff3b8:  0x0000000004069e90 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff3f0
0x00007ffeefbff3c8:  0x000000000400e9ce <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000030
0x00007ffeefbff3d8:  0x0000000000000010  0x0000000006c9c3c0
0x00007ffeefbff3e8:  0x0000000000000948  0x000000c0000001a0
0x00007ffeefbff3f8:  0x0000000004067fa9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff408:  0x0000000005d92500  0x0000000006c66760
0x00007ffeefbff418:  0x00007ffeefbff468  0x0000000004067ea5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff428:  0x0000000004067e5d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x57dcece, 0x6c66760})
	runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2052ac9e
stack: frame={sp:0x7ffeefbff328, fp:0x7ffeefbff378} stack=[0x7ffeefb803c8,0x7ffeefbff430)
0x00007ffeefbff228:  0x01007ffeefbff248  0x0000000000000004
0x00007ffeefbff238:  0x000000000000001f  0x00007fff2052ac9e
0x00007ffeefbff248:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff258:  0x0000000004036511 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8
0x00007ffeefbff268:  0x00000000057c2037  0x00007ffeefbff2b0
0x00007ffeefbff278:  0x00000000040367c8 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000006c66760
0x00007ffeefbff288:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff298:  0x00007ffeefbff2f8  0x0000000004036511 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2a8:  0x0000000006c66760  0x00007ffeefbff2e8
0x00007ffeefbff2b8:  0x0000000004036750 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff2c8
0x00007ffeefbff2c8:  0x0000000004036780 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000006c66760
0x00007ffeefbff2d8:  0x0000000004036511 <runtime.throw+0x0000000000000071>  0x00007ffeefbff2f8
0x00007ffeefbff2e8:  0x00007ffeefbff318  0x0000000004036511 <runtime.throw+0x0000000000000071>
0x00007ffeefbff2f8:  0x00007ffeefbff300  0x0000000004036540 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff308:  0x00000000057dcece  0x000000000000002a
0x00007ffeefbff318:  0x00007ffeefbff368  0x000000000404cc96 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff328: <0x00000000057dcece  0x0000000006c66760
0x00007ffeefbff338:  0x00007ffeefbff3a8  0x0000000004027686 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff348:  0x000000c000246000  0x0000000000002000
0x00007ffeefbff358:  0x0000000000000008  0x000000000406ba00 <runtime.walltime_trampoline+0x0000000000000000>
0x00007ffeefbff368:  0x00007ffeefbff3b0 !0x00007fff2052ac9e
0x00007ffeefbff378: >0x00007ffeefbff3b0  0x0000000006b08000
0x00007ffeefbff388:  0x00000000000004b7  0x0000000004497945 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff398:  0x000000000406c03f <runtime.syscall+0x000000000000001f>  0x000000c0000ed710
0x00007ffeefbff3a8:  0x0000000006c670c0  0x000000c0000ed6e0
0x00007ffeefbff3b8:  0x0000000004069e90 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff3f0
0x00007ffeefbff3c8:  0x000000000400e9ce <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000030
0x00007ffeefbff3d8:  0x0000000000000010  0x0000000006c9c3c0
0x00007ffeefbff3e8:  0x0000000000000948  0x000000c0000001a0
0x00007ffeefbff3f8:  0x0000000004067fa9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff408:  0x0000000005d92500  0x0000000006c66760
0x00007ffeefbff418:  0x00007ffeefbff468  0x0000000004067ea5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff428:  0x0000000004067e5d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x4497940, 0x1, 0x40487413, 0xc0000ed7a0)
	runtime/sys_darwin.go:22 +0x3b fp=0xc0000ed710 sp=0xc0000ed6f0 pc=0x406689b
syscall.syscall(0x40ade86, 0x0, 0xc0000ed7c8, 0x40addb8)
	<autogenerated>:1 +0x26 fp=0xc0000ed758 sp=0xc0000ed710 pc=0x406c846
golang.org/x/sys/unix.ioctl(0x574c249, 0x4, 0x100c00022f090)
	golang.org/x/sys@v0.0.0-20200905004654-be1d3432aa8f/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc0000ed788 sp=0xc0000ed758 pc=0x4497339
golang.org/x/sys/unix.IoctlGetTermios(...)
	golang.org/x/sys@v0.0.0-20200905004654-be1d3432aa8f/unix/ioctl.go:72
github.com/mattn/go-isatty.IsTerminal(0x574c249)
	github.com/mattn/go-isatty@v0.0.12/isatty_bsd.go:10 +0x50 fp=0xc0000ed7f8 sp=0xc0000ed788 pc=0x4497a30
github.com/fatih/color.init()
	github.com/fatih/color@v1.7.0/color.go:21 +0x7a fp=0xc0000ed830 sp=0xc0000ed7f8 pc=0x44e1ada
runtime.doInit(0x6b15aa0)
	runtime/proc.go:6498 +0x123 fp=0xc0000ed968 sp=0xc0000ed830 pc=0x4045e23
runtime.doInit(0x6b22b00)
	runtime/proc.go:6475 +0x71 fp=0xc0000edaa0 sp=0xc0000ed968 pc=0x4045d71
runtime.doInit(0x6b27c20)
	runtime/proc.go:6475 +0x71 fp=0xc0000edbd8 sp=0xc0000edaa0 pc=0x4045d71
runtime.doInit(0x6b18140)
	runtime/proc.go:6475 +0x71 fp=0xc0000edd10 sp=0xc0000edbd8 pc=0x4045d71
runtime.doInit(0x6b30820)
	runtime/proc.go:6475 +0x71 fp=0xc0000ede48 sp=0xc0000edd10 pc=0x4045d71
runtime.doInit(0x6b18ac0)
	runtime/proc.go:6475 +0x71 fp=0xc0000edf80 sp=0xc0000ede48 pc=0x4045d71
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc0000edfe0 sp=0xc0000edf80 pc=0x4038b66
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0000edfe8 sp=0xc0000edfe0 pc=0x406a181
`

**Comment by kawaiier** [comment] 2021-09-09 07:26
Same problem.
wtfutil 0.39.0 from Homebrew, macOS 11.5.2

**Comment by senorprogrammer** [comment] 2021-09-09 16:04
Could you let me know what OS you're running on?

**Comment by mar10p** [comment] 2021-09-09 23:17
Same issue here, also on macOS ver 11.5.2

**Comment by senorprogrammer** [comment] 2021-09-09 23:37
`brew install wtfutil` works for me on an M1 Mac Mini, fails with the error above on an Intel MacBook. This version was compiled on the M1. Curious if that's the cause.

**Comment by senorprogrammer** [comment] 2021-09-09 23:44
`go run .` fails on the MacBook, works on the M1. Interesting.

**Comment by senorprogrammer** [comment] 2021-09-10 04:09
Looks to me like this same issue https://github.com/sirupsen/logrus/issues/1275

Patching `golang.org/x/sys` has it working on my MacBook again.

**Comment by senorprogrammer** [comment] 2021-09-10 04:15
v0.39.2 has been released to address this issue. I'm going to leave this open until it's confirmed fixed by someone else. Thanks to @ejdunn2001 for reporting it quickly, and @kawaiier for adding the additional debugging info.

**Comment by mar10p** [comment] 2021-09-10 18:17
@senorprogrammer 0.39.2 confirmed working for me via homebrew upgrade. Thank you for the quick fix!!

**Comment by senorprogrammer** [comment] 2021-09-10 18:36
Awesome, thanks for confirming @mar10p

**Closed by senorprogrammer** 2021-09-10 18:36 UTC
Labels: 🐛 bug, 👍 confirmed, critical
