### ISSUE TITLE
Multiple instances of textfile

### ISSUE THREAD

**Issue by alienrobotarmy** [wtfutil/wtf#309] opened 2018-08-28 18:24 UTC
#### What problem does this solve?
This would allow multiple instances of textfile

#### How do envision it working?
Allow the user to add multiple textfile stanzas in the config.yml to allow displaying multiple text files

**Comment by iafan** [comment] 2019-01-19 19:38
This looks like a duplicate of #181

**Comment by senorprogrammer** [comment] 2019-05-03 00:18
With this PR https://github.com/wtfutil/wtf/pull/418 this is now possible. Documentation will be forthcoming.

**Closed by senorprogrammer** 2019-05-03 00:18 UTC
Labels: 💥 feature
