### ISSUE TITLE
CmdRunner not visualise hyperlinks

### ISSUE THREAD

**Issue by DimitarPetrov** [wtfutil/wtf#531] opened 2019-08-17 16:47 UTC
I have a script which prints hyperlinks to the console like this:
```
echo -e '\e]8;;http://example.com\aThis is a link\e]8;;\a'
```
which results in a hyperlink in the console but unfortunately it is not visualised in the wtf dashboard when executing the same script with CmdRunner.

**Comment by Seanstoppable** [comment] 2019-08-17 19:14
Do you mind providing a few more details here?

Running this gives me:

```\e]8;;http://example.comThis is a link\e]8;;``` On the OSX console and in wtfutil

**Comment by DimitarPetrov** [comment] 2019-08-17 19:47
Hi @Seanstoppable,

When further investigated this issue it seems like such a hyperlink printing in console works with zsh and not with bash. In a script looking like this:
```
#!/bin/zsh

echo -e '\e]8;;http://example.com\aThis is a link\e]8;;\a'
```
It works like this:
![image](https://user-images.githubusercontent.com/26522214/63216605-5b93ee80-c140-11e9-8dc4-54b09304b01e.png)

When you click on this while holding CMD it opens example.com
And with this setup when the same script is executed in CmdRunner widget in wtfutil nothing is printed.

**Comment by Seanstoppable** [comment] 2019-08-18 15:15
Got it! Able to replicate now.
I've tracked it back to https://github.com/rivo/tview/issues/108.

Essentially, this needs to be supported by the underlying renderer, and while the issue is marked closed, it doesn't seem resolved in either tview or tcell.

**Comment by senorprogrammer** [comment] 2021-04-25 22:05
Closing this because this is an issue for the underlying libraries (specifically tcell). Should tcell ever support it, WTF will gain it automatically.

**Closed by senorprogrammer** 2021-04-25 22:05 UTC
Labels: 💪 improvement
