### ISSUE TITLE
Todoist module not showing tasks

### ISSUE THREAD

**Issue by quantuminati** [wtfutil/wtf#556] opened 2019-08-29 05:05 UTC
If I have 3 or less tasks in my todoist inbox things work great, once I have 4 or more the wtfutil todoist module does not display anything (completely blank).

If I have 4 inbox tasks and then delete or move one within todoist, I can then use the "r" keyboard shortcut within wtfutil to see the 3 remaining tasks.

Unfortunately I'm not the type to have my life organized sufficiently to only have 3 or less open tasks.

Running on mac os 10.14.6, default shell, wtfutil -v indicates "dev", installed via homebrew

**Comment by senorprogrammer** [comment] 2019-08-29 05:16
Strange, I'm using Todoist and am not able to reproduce. Could you include a screenshot of that widget and your `Todoist` config yaml (remove the `apiKey` of course)?

**Comment by quantuminati** [comment] 2019-08-29 15:48
Awesome, thanks for the help. I've created the following config file and now the limit of what can be visible does not appear to be consistent. I was able to get 9 items to appear, but now it seems like 5 or 6 is the limit. Sometimes a refresh (r shortcut key) works, sometimes I need a full restart of wtfutil.

Here is my simplified config

`wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [45]
    rows: [20]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    todoist:
      apiKey: "something_secret"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      projects:
        - 2216424391
      refreshInterval: 3600
`

Working with 5 items: 
![image](https://user-images.githubusercontent.com/35411400/63955307-5769aa00-ca39-11e9-8c2d-47fea611ce00.png)

This time I had to add 7 items and then refresh (r shortcut key) results in blank:
![image](https://user-images.githubusercontent.com/35411400/63955437-8e3fc000-ca39-11e9-8803-2af7ebb626eb.png)

In todoist:
![image](https://user-images.githubusercontent.com/35411400/63955489-a1eb2680-ca39-11e9-9131-4602272fa5ad.png)

Without restarting I then remove an item from todoist
![image](https://user-images.githubusercontent.com/35411400/63955574-c941f380-ca39-11e9-8ec2-52c6391ff786.png)



And then it works after activating the refresh shortcut in wtfutil
![image](https://user-images.githubusercontent.com/35411400/63955557-c0512200-ca39-11e9-8e03-cb4d5147f8cb.png)

**Comment by senorprogrammer** [comment] 2019-08-29 16:24
What terminal/os are you on? I have a few guesses about this, but nothing concrete yet.

**Comment by quantuminati** [comment] 2019-08-29 17:56
Thank you!!

Running "Terminal" on mac os 10.14.6, default shell, wtfutil -v indicates "dev", installed via homebrew.

env | grep -i sh
SHELL=/bin/bash

/bin/bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by Seanstoppable** [comment] 2019-08-30 01:20
I am pretty confident this is an API issue. Either a timeout or a rate limit, or some other problem. The module hides api errors, and I'll be taking a crack at surfacing so we can debug better.

**Comment by quantuminati** [comment] 2019-08-30 22:09
Thanks! Appreciate any help you can provide, and now FYI things seem to be working effectively, I'm up to 11 tasks being displayed correctly, but if issues happen again, I imagine the additional info might help.

**Comment by Seanstoppable** [comment] 2019-09-01 15:55
Master should have fixes that catch and display errors, so we should hopefully be able to get more detail if it happens.

**Comment by deepkanwal** [comment] 2019-09-02 16:39
FYI, I'm encountering a blank Todoist widget as well. Logs indicate that a different API endpoint should be used:

<img width="330" alt="Screen Shot 2019-09-02 at 12 30 41 PM" src="https://user-images.githubusercontent.com/2261378/64127018-11d11800-cd7e-11e9-9ef2-118e19c2e033.png">

Seems like the darkSasori Todoist API implementation is using https://beta.todoist.com/API/v8/ ([src](https://github.com/darkSasori/todoist/blob/ec6b38b374ab9c60cc9716d2083ae66eb9383d03/todoist.go#L15)).

**Comment by Seanstoppable** [comment] 2019-09-02 22:25
Yeah, I've submitted a PR already, and if no movement, I'll do a fork/update

**Comment by senorprogrammer** [comment] 2019-09-02 22:29
Apologies guys, I've been ill all weekend. @Seanstoppable if the PR works for you and you're confident, by all means please merge.

**Comment by senorprogrammer** [comment] 2019-09-05 04:57
This PR has been merged into `master`: https://github.com/wtfutil/wtf/pull/602

**Comment by quantuminati** [comment] 2019-09-16 20:32
Thanks so much for looking into and repairing this!!

After an update my todist list of 10 items is showing correctly, but the "j/k" keyboard shortcut to navigate is interesting...

As for general items, I've seen some interesting results when I include text that I use tput to color code parts, IE: this at terminal

![image](https://user-images.githubusercontent.com/35411400/64991221-508ac600-d886-11e9-82c4-4ee1046cf3dc.png)

And this in wtfutil

![image](https://user-images.githubusercontent.com/35411400/64991248-5f717880-d886-11e9-90e5-eeee96adea23.png)

**Comment by senorprogrammer** [comment] 2019-09-19 05:17
Closing this as resolved for missing todo items.

**Closed by senorprogrammer** 2019-09-19 05:17 UTC
Labels: 🐛 bug
